name: Release to Beta Channel

on:
  push:
    branches:
      - master
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    env:
      GRADLE_OPTS: "-Xmx6g -Xms4g"
    steps:
      - name: Set current date as env variable
        run: echo "SNAPSHOT_SUFFIX=$(date +'%Y%m%d%H%M')" >> $GITHUB_ENV
      - uses: actions/checkout@v1
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: zulu
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: publishPlugin -PpublishPluginChannels=beta -PpublishPluginToken=${{ secrets.JB_PLUGINS_TOKEN }} -PideVersion=IC-2022.3 -PgroovyVersion=3.0.9 -PspockVersion=2.0-groovy-3.0 -PpluginVersion=6.0.0-${{ env.SNAPSHOT_SUFFIX }}
