on:
  repository_dispatch:
    types: [codenarc-new-version]
jobs:
  update-bom:
    name: Updates Version and Opens PR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Upgrade CodenarcVersion Number
        run: |
          export CODENARC_VERSION=$(curl https://repo1.maven.org/maven2/org/codenarc/CodeNarc/maven-metadata.xml | xpath '/metadata/versioning/latest/text()')
          sed -i "s/codenarcVersion.*/codenarcVersion=$CODENARC_VERSION/' gradle.properties
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: eskatos/gradle-command-action@v1
        name: Regenerate Inspection Tool Classes
        with:
          arguments: run --stacktrace
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Upgraded to the latest CodeNarc
          title: '[Ugrade] Upgraded to the latest CodeNarc version'
          body: |
            There is a newer version of codenarc available. The dependency has been updated and the inspection tools
            have been regenerated.
          labels: chore,upgrade
          assignees: musketyr
          branch: upgrade/codenarc
      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
