name: Check

on: [push, pull_request]
jobs:
  check:
    name: Run Tests
    runs-on: ubuntu-latest
    env:
      GRADLE_OPTS: "-Xmx6g -Xms4g"
      CI: true
    steps:
      - uses: actions/checkout@v1

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: test --stacktrace
      - name: Show Reports
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: reports
          path: build/reports/
  verify:
    name: Verify Plugin
    runs-on: ubuntu-latest
    env:
      GRADLE_OPTS: "-Xmx6g -Xms4g"
      CI: true
    steps:
      - uses: actions/checkout@v1

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: runPluginVerifier --stacktrace
      - name: Show Reports
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: reports
          path: build/reports/
