name: Check

on: [push, pull_request]
jobs:
  check:
    name: Run Tests
    runs-on: ubuntu-latest
    env:
      GRADLE_OPTS: "-Xmx6g -Xms4g"
      CI: true
    strategy:
      fail-fast: false # we need to know which version is failing
      matrix:
        version:
          - "-PideVersion=IC-2022.1 -PgroovyVersion=3.0.9 -PspockVersion=2.0-groovy-3.0"
    steps:
      - uses: actions/checkout@v1

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: test runPluginVerifier ${{ matrix.version }} --stacktrace
      - name: Show Reports
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: reports
          path: build/reports/
